name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Set the permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment
      run: |
        echo "DEBUG=False" > .env
        echo "SECRET_KEY=temp_key_for_build" >> .env
        echo "ALLOWED_HOSTS=*" >> .env
    
    - name: Create empty static directory
      run: |
        mkdir -p static
        touch static/.gitkeep
    
    - name: Run export script
      run: |
        python manage.py collectstatic --noinput
        python manage.py export_to_gh_pages
    
    - name: Create .nojekyll file
      run: touch docs/.nojekyll
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: 'docs/'
        branch: gh-pages
        clean: true
        force: true
        token: ${{ secrets.GITHUB_TOKEN }}
        target-folder: '.'  # Deploy contents of docs/ to root of gh-pages
    
    - name: Show deployment status
      run: |
        echo "Deployment status: ${{ steps.deployment.outcome }}"
        echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
