name: Django CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment
      run: |
        echo "DEBUG=False" > .env
        echo "SECRET_KEY=temp_key_for_build" >> .env
        echo "ALLOWED_HOSTS=*" >> .env
    
    - name: Run migrations
      run: python manage.py migrate --noinput
    
    - name: Collect static files
      run: python manage.py collectstatic --noinput
    
    - name: Export static site
      run: python manage.py export_to_gh_pages
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: 'docs/'
        branch: gh-pages
        clean: true
        force: true
