name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
# Set the permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment
        run: |
          echo "DEBUG=False" > .env
          echo "SECRET_KEY=temp_key_for_build" >> .env
          echo "ALLOWED_HOSTS=*" >> .env

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: docs/
          retention-days: 1

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site
          path: ./deploy
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          environment_name: github-pages
